# Generated by Django 5.2.12 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('BASE', 'Phí gốc'), ('PENALTY', 'Phí phạt đỗ quá hạn'), ('TOWING', 'Phí cẩu xe')], default='BASE', max_length=10),
        ),
    ]
