# Generated by Django 6.0.2 on 2026-02-28 09:01

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('fee_type', models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô')], max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='Giá (VNĐ)')),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Tên/đời xe – ví dụ: Yamaha Sirius', max_length=255)),
                ('license_plate', models.CharField(help_text='Biển số xe', max_length=15, unique=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, help_text='Ảnh xe', max_length=255, null=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô')], max_length=20)),
                ('is_approved', models.BooleanField(default=False, help_text='Đã được admin duyệt chưa')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('fee', models.PositiveIntegerField(blank=True, help_text='Phí phải trả cho lượt này', null=True)),
                ('status', models.CharField(choices=[('IN', 'Đang gửi'), ('OUT', 'Đã lấy xe')], default='IN', max_length=4)),
                ('fee_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_logs', to='parking.feerule')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
