# Generated by Django 5.1.6 on 2026-03-17 09:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='VehicleFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(max_length=100, verbose_name='Tên người lái')),
                ('relationship', models.CharField(max_length=10, verbose_name='Quan hệ với chủ xe')),
                ('face_img', cloudinary.models.CloudinaryField(max_length=255)),
                ('face_vector', models.JSONField(verbose_name='Vector đặc trưng')),
                ('is_default', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parking.vehicleface')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='parking.vehicle')),
            ],
            options={
                'ordering': ['-is_default'],
            },
        ),
    ]
