# Generated by Django 5.1.6 on 2026-03-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_feerule_id_alter_parkinglog_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô'), ('TRUCK', 'Xe tải'), ('BUS', 'Xe bus')], default='Car', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feerule',
            name='fee_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô'), ('TRUCK', 'Xe tải'), ('BUS', 'Xe bus')], max_length=10),
        ),
    ]
