# Generated by Django 5.1.6 on 2026-03-20 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_vehicle_vehicle_type_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglog',
            name='vehicle_face',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='parking_logs', to='parking.vehicleface'),
            preserve_default=False,
        ),
    ]
