# Generated by Django 5.2.12 on 2026-03-30 12:32

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_alter_feerule_id_alter_parkinglog_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_slots', models.PositiveIntegerField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('threshold_release', models.FloatField(default=0.8)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='feerule',
            name='parking_lot',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='fee_rules', to='parking.parkinglot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='parking_lot',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='parking_logs', to='parking.parkinglot'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('slot_number', models.CharField(max_length=50, unique=True)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_look_up', models.BooleanField(default=False)),
                ('is_force_released', models.BooleanField(default=False)),
                ('raw_index', models.PositiveIntegerField(help_text='Hàng thứ mấy')),
                ('column_index', models.PositiveIntegerField(help_text='Cột thứ mấy')),
                ('floor', models.IntegerField(default=1)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(help_text='Thời gian xe đến')),
                ('end_time', models.DateTimeField(blank=True, help_text='Thời gian dự kiến rời đi', null=True)),
                ('deposit_amount', models.PositiveIntegerField(help_text='Phí đặt chỗ')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ thanh toán cọc'), ('CONFIRMED', 'Đã đặt chỗ thành công'), ('CHECKED_IN', 'Đã vào bãi'), ('CANCELLED', 'Khách hàng hủy'), ('EXPIRED', 'Quán hạn không đến (mất cọc)')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.vehicle')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
