# Generated by Django 5.2.12 on 2026-03-30 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_parkinglot_feerule_parking_lot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='total_slots',
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='bus_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='car_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='moto_slots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='truck_slots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
