# Generated by Django 5.2.12 on 2026-03-31 10:38

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_remove_parkinglot_total_slots_parkinglot_bus_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='image',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='column_index',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='raw_index',
        ),
        migrations.CreateModel(
            name='MapSvg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('map_svg', cloudinary.models.CloudinaryField(blank=True, help_text='Upload file sơ đồ SVG', max_length=255, null=True)),
                ('floor', models.PositiveIntegerField(default=0)),
                ('floor_display', models.CharField(max_length=255)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_svgs', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
    ]
