# Generated by Django 5.2.12 on 2026-04-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_remove_parkinglot_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingslot',
            options={},
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_type',
            field=models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô'), ('TRUCK', 'Xe tải'), ('BUS', 'Xe bus')], default='CAR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='parkingslot',
            constraint=models.UniqueConstraint(fields=('parking_lot', 'slot_number'), name='unique_parking_slot_per_lot'),
        ),
    ]
