# Generated by Django 5.2.12 on 2026-04-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_alter_parkingslot_options_parkingslot_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapsvg',
            options={},
        ),
        migrations.AddField(
            model_name='booking',
            name='expired_time',
            field=models.DateTimeField(default='2026-04-02T15:30:00Z', help_text='Thời gian hết hạn'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(help_text='Thời gian xe ra'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán cọc'), ('ACTIVE', 'Đã đặt'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Khách hàng hủy'), ('EXPIRED', 'Quán hạn không đến (mất cọc)')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='mapsvg',
            constraint=models.UniqueConstraint(fields=('parking_lot', 'floor'), name='unique_map_per_floor_per_lot'),
        ),
    ]
