# Generated by Django 5.2.12 on 2026-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_alter_mapsvg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán cọc'), ('ACTIVE', 'Đã đặt'), ('CHECK_IN', 'Đã vào cổng'), ('PARKING', 'Đang thực hiện đỗ'), ('COMPLETED', 'Hoàn tất'), ('CANCELLED', 'Khách hàng hủy'), ('EXPIRED', 'Quán hạn không đến (mất cọc)')], default='PENDING', max_length=10),
        ),
    ]
