# Generated by Django 5.2.12 on 2026-04-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_remove_parkingslot_is_force_released_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceStrategyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('WEEKEND', 'Cuối tuần'), ('HOLIDAY', 'Ngày lễ'), ('OCCUPANCY', 'Xe đông')], help_text='Vd: WEEKEND, HOLIDAY, OCCUPANCY', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLotPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('multiplier', models.FloatField(default=1.0, help_text='Hệ số nhân giá (Vd: 1.5)')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='parking.parkinglot')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.pricestrategytemplate')),
                ('holiday', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parking.publicholiday')),
            ],
            options={
                'unique_together': {('parking_lot', 'strategy', 'holiday')},
            },
        ),
    ]
