# Generated by Django 5.2.12 on 2026-04-05 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0013_pricestrategytemplate_publicholiday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expired_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text='Tổng tiền đỗ xe dự tính (100% tiền thuê chỗ)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='lot',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkinglot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='final_amount_to_pay',
            field=models.PositiveIntegerField(blank=True, help_text='Số tiền thực tế thu tại cổng', null=True),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, help_text='Xe đang đỗ trông ô booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='parking.vehicle'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='deposit_amount',
            field=models.PositiveIntegerField(default=0, help_text='Phí đặt chỗ (20% của total_fee)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ thanh toán'), ('ACTIVE', 'Đã đặt'), ('PARKING', 'Đang đỗ xe'), ('COMPLETED', 'Hoàn tất'), ('EXPIRED', 'Hết hạn sử dụng')], default='PENDING', max_length=10),
        ),
    ]
