# Generated by Django 5.2.12 on 2026-04-06 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_remove_booking_expired_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglog',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
