# Generated by Django 5.2.12 on 2026-04-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_remove_parkingslot_is_force_released_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parkinglotpolicy',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parkinglotpolicy',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='parkinglotpolicy',
            name='parking_lot',
        ),
        migrations.RemoveField(
            model_name='parkinglotpolicy',
            name='strategy',
        ),
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
        migrations.DeleteModel(
            name='ParkingLotPolicy',
        ),
        migrations.DeleteModel(
            name='PriceStrategyTemplate',
        ),
    ]
