# Generated by Django 5.2.12 on 2026-04-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_alter_parkinglotpolicy_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='current_vehicle',
        ),
        migrations.RemoveField(
            model_name='parkingslot',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='booking',
            name='expired_time',
            field=models.DateTimeField(default='2026-04-09', help_text='Thời gian hết hạn'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_logs', to='parking.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parking.parkingslot'),
        ),
    ]
