# Generated by Django 5.2.12 on 2026-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_remove_booking_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglog',
            name='fee',
            field=models.PositiveIntegerField(blank=True, help_text='Tổng phí', null=True),
        ),
    ]
