# Generated by Django 5.2.12 on 2026-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0018_remove_parkingslot_is_force_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overtime_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
