# Generated by Django 5.2.12 on 2026-04-10 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0019_remove_parkingslot_is_force_released_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkinglot',
            name='threshold_release',
        ),
    ]
