# Generated by Django 5.2.12 on 2026-05-21 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0021_remove_parkingslot_is_force_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('package_name', models.CharField(max_length=100, verbose_name='Tên gói cước')),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Xe máy'), ('CAR', 'Ô tô'), ('TRUCK', 'Xe tải'), ('BUS', 'Xe bus')], max_length=20, verbose_name='Loại xe áp dụng')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá gói (VNĐ)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_packages', to=settings.AUTH_USER_MODEL)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='parking.parkinglot')),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày hết hạn')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Đã hết hạn'), ('pending', 'Chờ thanh toán'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle', verbose_name='Biển số xe đăng ký')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.subscriptionpackage', verbose_name='Gói cước')),
            ],
            options={
                'verbose_name': 'Đăng ký vé tháng',
                'verbose_name_plural': 'Danh sách đăng ký vé tháng',
                'ordering': ['-created_date'],
            },
        ),
    ]
