# Generated by Django 5.2.12 on 2026-05-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0022_remove_parkingslot_is_force_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscription',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Giá gói (VNĐ)'),
            preserve_default=False,
        ),
    ]
