# Generated by Django 5.2.12 on 2026-03-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMIN', 'Quản trị viên'), ('MANAGE', 'Quản lý'), ('STAFF', 'Nhận viên'), ('CUSTOMER', 'Khách hàng')], default='CUSTOMER', max_length=10),
        ),
    ]
