# Generated by Django 5.2.12 on 2026-03-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
