# Generated by Django 5.2.12 on 2026-05-01 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('OPERATOR', 'Giám sát vận hành'), ('TECHNICAL', 'Kỹ thuật viên'), ('MARSHAL', 'Điều phối'), ('INCIDENT', 'Xử lý sự cố')], max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parkinglot')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobposition')),
            ],
        ),
    ]
